site_name: actions-test-005
site_description: 
repo_url: https://github.com/rhdh-skitamura-org/actions-test-005-app
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# Note for content editors, edit only the section below
nav:
  - actions-test-005 Documentation: index.md
